config/routes.rb
CMUEducation::Application.routes.draw do


  #temporary for Mel
  match 'courses/:course_id/team_deliverables' => 'deliverables#team_index_for_course', :as => :individual_deliverables
  match 'courses/:course_id/individual_deliverables' => 'deliverables#individual_index_for_course', :as => :team_deliverables

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  constraints(:host => /rails.sv.cmu.edu/) do
    match "/(*path)" => redirect {|params, req| "http://whiteboard.sv.cmu.edu/#{params[:path]}"}
  end

  resources :search, :only => [:index]
  #get    "/deliverables/get_assignments_for_student(.:format)" =>  "deliverables#get_assignments_for_student"

  resources :password_resets

  match '/deliverables/get_assignments_for_student(.:format)'=> 'deliverables#get_assignments_for_student' ,:as=> :get_assignments_for_student
  resources :deliverables

  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/people/:id/my_presentations' => 'presentations#my_presentations', :as => :my_presentations

  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/presentations/:id/show_feedback' => 'presentations#show_feedback', :as => :show_feedback_for_presentation, :via => :get
  match '/presentations/:id/edit_feedback' => 'presentations#update_feedback', :via => :put
  match '/presentations/:id/edit_feedback' => 'presentations#edit_feedback', :as => :edit_feedback_for_presentation, :via => :get
  match '/presentations/:id/feedback' => 'presentations#create_feedback', :via => :post
  match '/presentations/:id/feedback' => 'presentations#new_feedback', :as => :new_presentation_feedback, :via => :get
  match '/presentations/today' => 'presentations#today', :as => :today_presentations
  resources :presentations, :only => [:index]

  match '/jobs/assignments' => 'jobs#assignments', :as => :job_assignments
  resources :jobs

  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :page_comment_types
  resources :page_comments
  resources :scotty_dog_sayings
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations

  match '/courses/current_semester' => redirect("/courses/semester/#{AcademicCalendar.current_semester()}#{Date.today.year}"), :as => :current_semester
  match '/courses/next_semester' => redirect("/courses/semester/#{AcademicCalendar.next_semester()}#{AcademicCalendar.next_semester_year}"), :as => :next_semester
  match '/course/:course_id/grades/send_final_grade' => 'grades#send_final_grade', :as=>:send_final_grade, :via => :post
  match '/course/:course_id/grades/post_drafted_and_send' => 'grades#post_drafted_and_send', :as=>:post_drafted_and_send, :via => :post
  match '/course/:course_id/grades/save' => 'grades#save', :as=>:save, :via => :post
  match '/course/:course_id/grades/export' => 'grades#export', :as=>:export, :via => :post
  match '/course/:course_id/grades/import' => 'grades#import', :as=>:import, :via => :post

  resources :courses do
    resources :assignments
    resources :grades
  end

  match '/course/:course_id/assignments/reposition' => 'assignments#show', :as=>:assignments_show, :via => :get
  match '/course/:course_id/assignments/reposition' => 'assignments#reposition', :as=>:assignments_reposition, :via => :post

  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
        get :changed
      end
      member {post :revert}
    end
  end

  resources :page_attachments

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
      get :tool_support
    end
    resources :presentations, :only => [:new, :edit, :create, :update]
  end


  match 'courses/semester/:semester' => 'courses#index_for_semester', :as => "semester_courses"
  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people_autocomplete' => 'people#index_autocomplete'
  match '/people_search' => 'people#search'

  match '/people_csv' => 'people#download_csv'
  match '/people_vcf' => 'people#download_vcf'

  match '/people/class_profile' => 'people#class_profile'
  match '/people/ajax_check_if_email_exists' => 'people#ajax_check_if_email_exists'
  match '/people/ajax_check_if_webiso_account_exists' => 'people#ajax_check_if_webiso_account_exists'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses_verbose' => 'people#my_courses_verbose', :as => :my_courses
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  match '/people/:id/upload_photo' => 'people#upload_photo', :as => :people_photo_upload, :via => :put
  resources :people
  resources :users, :controller => 'people'
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams



  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new', :via => :get
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv_old' => 'teams#export_to_csv'
  match 'courses/:course_id/export_to_csv' => 'courses#export_to_csv'
  match 'courses/:course_id/team_formation_tool' => 'courses#team_formation_tool', :as => :team_formation_tool
  match 'courses/:course_id/student_grades' => 'grades#student_deliverables_and_grades_for_course', :as => :course_student_grades
  match 'courses/:course_id/deliverables' => 'deliverables#grading_queue_for_course', :as => :course_deliverables
  match 'courses/:course_id/get_deliverables' => 'deliverables#get_deliverables', :as => :get_deliverables
  match 'courses/:course_id/filter_deliverables' => 'deliverables#filter_deliverables', :as => :filter_deliverables
  match 'courses/:course_id/update_feedback' => 'deliverables#update_feedback', :as => :update_feedback
  match 'courses/:course_id/presentations' => 'presentations#index_for_course', :as => :course_presentations



  #match 'courses/:course_id/presentations/update' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/edit' => 'presentations#edit', :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#new', :as => :new_course_presentation

  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'

  match 'static/:action' => 'static#:action'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root

end

app/models/person.rb
# Person is a versioned model representing user data. As described in the README,
# the Person model and the User model both represent the same database table.
#
# == Related classes
# {Person Controller}[link:classes/PeopleController.html]
#
# {User}[link:classes/User.html]
#
class Person < User
  set_table_name "users"


#  def to_param
#    if twiki_name.blank?
#      id.to_s
#    else
#      twiki_name
#    end
#  end


end

app/helpers/people_helper.rb
module PeopleHelper

  def display_location(person)
    return nil if (person.work_city.nil? && person.work_state.nil? && person.work_country.nil?)
    return "#{person.work_state} #{person.work_country}" if person.work_city.nil?
    return "#{person.work_city}, #{person.work_state} #{person.work_country}"
  end

  def linked_in_path(person)
    return "http#{$2}://www.linkedin.com/in/#{$7}" if person.linked_in =~ /(http)?(s)?(:\/\/)?(www.)?(linkedin.com\/)?(.*\/)?(.*)/
    return "http://www.linkedin.com/in/#{person.linked_in}"
  end
  def facebook_path(person)
    return "http#{$2}://www.facebook.com/#{$7}" if person.facebook =~ /(http)?(s)?(:\/\/)?(www.)?(facebook.com\/)?(.*\/)?(.*)/
    return "http://www.facebook.com/#{person.facebook}"
  end
  def twitter_path(person)
    return "http#{$1}://www.twitter.com/#{$2}" if person.twitter =~ /\[http\]?(s)?:\/\/\]?\[www\.\]?twitter\.com\/(.*)\/?/
    return "http://www.twitter.com/#{person.twitter}"
  end
  def google_plus_path(person)
    return "http#{$2}://plus.google.com/#{$7}" if person.google_plus =~ /(http)?(s)?(:\/\/)?(www.)?(plus.google.com\/)?(.*\/)?(\d+)(.*)/
    return "http://plus.google.com/#{person.google_plus}"
  end
  def github_path(person)
    return "http#{$1}://www.github.com/#{$2}" if person.github =~ /\[http\]?(s)?:\/\/\]?\[www\.\]?github\.com\/(.*)\/?/
    return "http://www.github.com/#{person.github}"
  end

end

app/views/people/_profile_photo.erb
<div class='team_member_photo'>
  <%= link_to "/people/#{person.twiki_name}", :target=>"_top" do  %>
    <%= image_tag(person.image_uri, :border => 0, :class => "user_profile_photo", :alt => person.human_name+" image") %><% end %>
  <br>
  <div class='label'><%= person.human_name %></div>
</div>

app/views/people/_show_telephones.html.erb
<% @person.telephones.each { |phone| %>
    <%= h phone %><br/>
<% } %>

app/views/people/_tablesorter_filter_box.erb
<!-- <div style='border-right: solid 3px #7f7f7f;'> -->
<div id='filterBox'>
  Filter: <input id='filterBoxOne' value='Page is still loading' disabled maxlength='30' size='30' type='text'/>
  <%= image_tag("tablesorter/cross.png", :width => "16", :height => "16", :id => "filterClearOne", :title => 'Click to clear filter.', :alt => 'Clear Filter Image') %>
</div>

app/views/people/_team_listing.html.erb
<% reset_cycle %>
<table class="twikiTable" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <th>Course</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th>Semester</th>
    <th>Year</th>
    <th width="100">Faculty</th>
    <th width="100">Faculty</th>
    <th>&nbsp;</th>
  </tr>
  <% teams.each do |team| %>
      <tr class=<%= cycle('twikiTableOdd', 'twikiTableEven') %>>
        <td><%= h team.course.name %></td>
        <% if !team.twiki_space.nil? && !team.twiki_space.empty? %>
            <td class="twikiFirstCol"><a href='<%= h team.twiki_space %>'><%= h team.name %></a></td>
        <% else %>
            <td class="twikiFirstCol"><%= h team.name %></td>
        <% end %>
        <% if !(team.email.nil? || team.email.empty?) %>
            <td>
              <a href='mailto:<%= h team.email %>'><%= image_tag("email.gif", :width => "12", :height => "9", :border => 0) %></a>
            </td>
        <% else %>
            <td> &nbsp; </td>
        <% end %>
        <% if !team.tigris_space.nil? && team.tigris_space.empty? %>
            <td>
              <a href='<%= h team.tigris_space %>'><%= image_tag("tigris.gif", :width => "16", :height => "16", :border => 0) %></a>
            </td>
        <% else %>
            <td> &nbsp; </td>
        <% end %>
        <td><%= h team.course.semester %></td>
        <td><%= h team.course.year %></td>
        <% if team.primary_faculty %>
            <td><%= link_to team.primary_faculty.human_name, person_path(team.primary_faculty.twiki_name) %></td>
        <% else %>
            <td>&nbsp;</td>
        <% end %>
        <% if team.secondary_faculty %>
            <td><%= link_to team.secondary_faculty.human_name, person_path(team.secondary_faculty.twiki_name) %></td>
        <% else %>
            <td>&nbsp;</td>
        <% end %>
        <td><%= link_to 'Show', course_team_path(team.course_id, team) %></td>
      </tr>
  <% end %>
</table>

app/views/people/advanced.erb
<% content_for :title, 'People' %>

<% content_for :tablesorter do %>

    <%= javascript_include_tag 'jquery_tablesorter_min.js' %>
    <%= javascript_include_tag 'jquery_quicksearch.js' %>

    <script type="text/javascript">
        $(document).ready(function () {
            var $search = $("#filterBoxOne");
            if ($search.prop("disabled") == true) {
                $search.val('');
                $search.removeAttr("disabled");
                $search.focus();
            }
            $("#people_table").tablesorter({
                // add zebra striping style
                widgets:['zebra'],
                // don't allow sorting on the picture and contact details columns
                headers:{0:{sorter:false}, 3:{sorter:false}}
            });
            $search.quicksearch('#people_table tbody tr');

            //scroll the message box to the top offset of browser's scrool bar
            $(window).scroll(function () {
                $('#image_box').animate({top:$(window).scrollTop() + "px" }, {queue:false, duration:350});
            });
            //when the close button at right corner of the message box is clicked
            $('#close_image_box').click(function () {
                //the messagebox gets scroll down with top property and gets hidden with zero opacity
                $('#image_box').animate({ top:"+=15px", opacity:0 }, "slow");
                $('#image_box').hide();
            });

            //hovering over a line selects it
            $("tr").hover(function () {
                $(this).addClass("hover");
            },function () {
                $(this).removeClass("hover");
            });
        });

        function toggleStudents() {
            /* we don't use .toggle since the state may be inaccurate from a page reload */
            if ($('#student_checkbox').is(':checked')) {
                $(".student").show();
            } else {
                $(".student").hide();
            }
            $("#filterBoxOne").trigger("keyup");
        }

        function toggleStaff() {
            if ($('#staff_checkbox').is(':checked')) {
                $(".staff").show();
            } else {
                $(".staff").hide();
            }
            $("#filterBoxOne").trigger("keyup");
        }

        function updateImage(uri, label) {
            $('#image_box_image').prop("src", uri);

            $('#image_box_label').text(label);
        }

    </script>
<% end %>

<h1>Listing people</h1>
<div class="right_link"><%= link_to 'See users book', :action => 'index' %>
  <br/><%= link_to 'See photo book', :action => 'photo_book' %></div>
<div style="float:none"><%= render :partial => "tablesorter_filter_box" %>
  <label>Show Students</label>
  <input type="checkbox" id="student_checkbox" onchange="toggleStudents()" value="1" checked="checked"/>
  <label>Show
    Staff</label><input type="checkbox" id="staff_checkbox" onchange="toggleStaff()" value="1" checked="checked"/>
</div>

<div id="image_box">
  <%= image_tag("mascot.jpg", :width => "150", :alt => "Temporary Picture", :id => "image_box_image") %><%= image_tag("tablesorter/cross.png", :width => "16", :height => "16", :alt => "Close Me", :style => "float:right;cursor:pointer", :id => "close_image_box") %>
  <div id='image_box_label'></div>
</div>

<% if current_user && (current_user.is_admin? || current_user.is_staff?) %>
    <%= link_to 'New person', new_person_path %>
<% end %>

<table id="people_table" class="tablesorter">
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Icons</th>
    <th>Graduation year</th>
    <th>Graduate program</th>
    <th>Graduate track</th>
  </tr>
  </thead>
  <tbody>
  <% for person in @people %>

      <tr class="tablesorter
        <% if person.is_student %>student
        <% end %>
        <% if person.is_staff %>staff
        <% end %>" onmouseover="updateImage('<%= image_path(person.image_uri) %>','<%=person.human_name%>')">
        <td><%= link_to person.first_name, person_path(person.twiki_name) %></td>
        <td><%= link_to person.last_name, person_path(person.twiki_name) %></td>
        <td>
          <a href='http://info.sv.cmu.edu/twiki/bin/view/Main/<%= person.twiki_name %>' target='_top'><%= image_tag('twiki.gif', :width => '16', :height => '16', :border => "0", :alt => "My TWiki page", :title => "My TWiki page") %></a>
          <% if person.is_adobe_connect_host %><%= image_tag("connect.gif", :width => "16", :height => "16", :alt => "Adobe Connect Host", :title => "I am Adobe Connect Host") %>
          <% end %>
          <% if current_user.is_staff? || current_user.is_admin? %>
              <%= link_to image_tag("my_teams2.gif", :width => "16", :height => "16", :alt => "My Teams", :title => "My Teams"), my_teams_path(person.id) %>
          <% end %>
        </td>
        <td><%= h person.graduation_year %></td>
        <td><%= h person.masters_program %></td>
        <td><%= h person.masters_track %></td>
        <td><%= link_to 'Show', person %></td>
        <% if current_user && current_user.is_staff? %>
            <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <% else %>
            <td>&nbsp;</td>
        <% end %>
        <!--
<% if current_user && current_user.is_admin? %>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
<% else %>
    <td>&nbsp;</td>
<% end %>
-->
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<% if current_user && (current_user.is_admin? || current_user.is_staff?) %>
    <%= link_to 'New person', new_person_path %>
<% end %>

app/views/people/my_courses.html.erb
<% content_for :title, 'My Courses for ' + @person.human_name %>

<h1>My courses</h1>
<% @registered_for_these_courses.each do |course| %>
    <p><%= link_to course.name, course_path(course) %></p>
    <%# render :partial => "/courses/show_actions" ,:locals => { :course => course } %>
<% end %>
<% @teaching_these_courses.each do |course| %>
    <p><%= link_to course.name, course_path(course) %></p>
    <%# render :partial => "/courses/show_actions" ,:locals => { :course => course } %>
<% end %>


<br/>

app/views/people/show.html.erb
<% content_for :title, @person.human_name + " - Contact Information" %>
<%= javascript_include_tag 'people_search_export' %>

<% content_for :javascript do %>
    <script type="text/javascript">
        $(document).ready(function(){
            var current_sign_in_ip = "<%= @person.current_sign_in_ip if can? :see_current_sign_in_ip, User %>";
            if(current_sign_in_ip != ""){
                $.get("http://api.hostip.info/get_json.php?ip=" + current_sign_in_ip, function(data,status){
                    if(status == 'success')
                        $("#geo_ip").html('<a href="https://maps.google.com/maps?q='+ data.city + '">' + data.city + '</a>');
                });
            }
        });
    </script>
<% end %>

<%= form_for(@person) do |f| %>
    <% if @person.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

          <ul>
            <% @person.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div id="user_profile_show">
        <div class="user_profile_content">
            <div class="user_profile_photo_social">
                <%= image_tag(@person.image_uri, :class=>"user_profile_photo") %>
                <div class="user_profile_social clearboth">

                    <% if !@person.linked_in.blank? %>
                        <%= link_to image_tag("icon_LinkedIn_gray.png", :id => "icon", :width => "24", :alt => "Linked in`", :title => "Linked In account"), linked_in_path(@person) %>
                    <% end %>

                    <% if !@person.facebook.blank? %>
                        <%= link_to image_tag("icon_Facebook_gray.png", :id => "icon", :width => "24", :alt => "Facebook", :title => "Facebook account"), facebook_path(@person) %>
                    <% end %>

                    <% if !@person.twitter.blank? %>
                        <%= link_to image_tag("icon_Twitter_gray.png", :id => "icon", :width => "24", :alt => "Twitter", :title => "Twitter account"), twitter_path(@person) %>
                    <% end %>

                    <% if !@person.google_plus.blank? %>
                        <%= link_to image_tag("icon_Google_gray.png", :id => "icon", :width => "24", :alt => "Google +", :title => "google+ account"), google_plus_path(@person) %>
                    <% end %>

                    <% if !@person.github.blank? %>
                        <%= link_to image_tag("icon_github.png", :id => "icon", :width => "24", :alt => "github", :title => "github account"), github_path(@person) %>
                    <% end %>

                </div>
            </div>

        <div class="user_profile_title">
      <input type="hidden" id="person_id" value="<%= @person.id %>" />
            <h1 id="user_profile_name">
                <%= h @person.first_name %> <%= h @person.last_name %>
                <% if !(@person.pronunciation.blank?) %>
                    <div class="user_profile_pron">Pronounced: <%= h @person.pronunciation %> <br /></div>
                <% end %>
            </h1>
            <div class="user_profile_action">
                <%= link_to 'Back', people_path %>
              <% if can? :update, @person %>
                 | <%= link_to 'Edit', edit_person_path(@person) %>
                <% end %>
            </div>
            <div id="user_profile_dtls">
                <% if @person.is_student %>
                    <%= h @person.masters_program %>
                    <% if !(@person.masters_track.blank?) %>(<%= h @person.masters_track %>)<% end %>
                    <% if @person.is_part_time %>
                        Part Time
                    <% else %>
                        Full Time
                    <% end %>
                    <% if !(@person.graduation_year.blank?) %>
                        (<%= h @person.graduation_year %>)
                    <% end %>
                <% elsif @person.is_staff %>
                    <%= @person.title %>
                <% end %>
                <% if (current_user.is_staff? || current_user.is_admin?) && @person.teams.count > 0 %>
                        <br /><%= link_to "My teams", my_teams_path(@person) %>
                <% end %>
                <br/><a  href="#" class="export_button" >Download contact details</a>
            </div>
        </div>

            <div class="user_profile_contact_details_content">
                <table class="cmu_table">
                    <tr>
                        <td>Email</td>
                        <td><a href='mailto:<%= @person.email %>'><%= h @person.email %></a></td>
                    </tr>
                    <%  @person.telephones_hash.each_with_index do |(key, value), index| %>
                    <tr <% if index.even? %> <% end %> >
                        <td><%= h "#{key}" %></td>
                        <td><%= h "#{value}" %></td>
                    </tr>
                    <%  end %>
                    <% if !(@person.skype.blank?) %>
                    <tr>
                        <td>Skype</td>
                        <td><%= h @person.skype %></td>
                    </tr>
                    <% end %>
                </table>

            <table class="cmu_table">

              <% if (!@person.organization_name.blank?) || (!@person.title.blank?) %>
                <tr>
                    <td>Organization</td>
                    <td>
                        <% if @person.organization_name %>
                            <% if @person.title %>
                                <%= h @person.title %> <br />
                            <% end %>
                            <%= h @person.organization_name %>
                        <% else %>
                            &nbsp;
                        <% end %>
                    </td>
                </tr>
              <% end %>

                <tr>
                    <td>Location</td>
                    <td>
                        <% if display_location(@person) %><%= h display_location(@person) %>
                        <% else %>&nbsp;
                        <% end %>
                    </td>
                </tr>
                <% if can? :see_current_sign_in_ip, User %>
                    <tr>
                        <td>Last signed in</td>
                        <td id="geo_ip">&nbsp;</td>
                    </tr>
                <% end %>
            </table>

            </div><!--  user_profile_contact_details -->



        <div class="clearboth">
          <% if !@person.biography.blank? %>
            <h2>Biography:</h2>
            <div class="user_profile_content_body"><%= sanitize @person.biography, :tags => %w(table tr td p br span img a h1 h2 h3 ul ol li), :attributes => %w(id class style) %></div>
          <% end %>
        </div><!-- user_profile_about -->

        <div class="clearboth ">
            <h2>Other Information:</h2>
            <table class="cmu_table">

              <% if !@person.personal_email.blank? %>
                <tr class="">
                <tr>
                    <td>Personal Email</td>
                    <td><a href='mailto:<%= @person.personal_email %>'><%= h @person.personal_email %></a></td>
                </tr>
              <% end %>
                <tr class="">
                    <td>Andrew Email</td>
                    <td><a href='mailto:<%= @person.webiso_account %>'><%= h @person.webiso_account %></a></td>
                </tr>

                <% if @person.is_staff %>
                <% if !@person.office.blank? %>
                <tr>
                  <td>Office:</td>
                  <td><%= h @person.office %></td>
                </tr>

                <% end %>
                <% if !@person.office_hours.blank? %>
                <tr class="">
                  <td>Office Hours:</td>
                  <td><%= h @person.office_hours %></td>
                </tr>
                <% end %>
                <% elsif @person.is_student %>
                <% unless @person.local_near_remote.blank? || @person.local_near_remote=="Unknown" %>
                <tr>
                  <td>Availability:</td>
                  <td>I am a  <%= h @person.local_near_remote.downcase %> student.</td>
                </tr>
                <% end %>
                <% end %>
            </table>
        </div>



    </div> <!-- user_profile_content -->

    <div class="user_profile_action">
        <%= link_to 'Back', people_path %>
        <%   if @person.id == current_user.id or current_user.is_admin? %>
            | <%= link_to 'Edit', edit_person_path(@person) %>
        <% end %>
    </div>
    </div><!-- user_profile_show -->

<% end %>