config/routes.rb
CMUEducation::Application.routes.draw do


  #temporary for Mel
  match 'courses/:course_id/team_deliverables' => 'deliverables#team_index_for_course', :as => :individual_deliverables
  match 'courses/:course_id/individual_deliverables' => 'deliverables#individual_index_for_course', :as => :team_deliverables

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  constraints(:host => /rails.sv.cmu.edu/) do
    match "/(*path)" => redirect {|params, req| "http://whiteboard.sv.cmu.edu/#{params[:path]}"}
  end

  resources :search, :only => [:index]
  #get    "/deliverables/get_assignments_for_student(.:format)" =>  "deliverables#get_assignments_for_student"

  resources :password_resets

  match '/deliverables/get_assignments_for_student(.:format)'=> 'deliverables#get_assignments_for_student' ,:as=> :get_assignments_for_student
  resources :deliverables

  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/people/:id/my_presentations' => 'presentations#my_presentations', :as => :my_presentations

  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/presentations/:id/show_feedback' => 'presentations#show_feedback', :as => :show_feedback_for_presentation, :via => :get
  match '/presentations/:id/edit_feedback' => 'presentations#update_feedback', :via => :put
  match '/presentations/:id/edit_feedback' => 'presentations#edit_feedback', :as => :edit_feedback_for_presentation, :via => :get
  match '/presentations/:id/feedback' => 'presentations#create_feedback', :via => :post
  match '/presentations/:id/feedback' => 'presentations#new_feedback', :as => :new_presentation_feedback, :via => :get
  match '/presentations/today' => 'presentations#today', :as => :today_presentations
  resources :presentations, :only => [:index]

  match '/jobs/assignments' => 'jobs#assignments', :as => :job_assignments
  resources :jobs

  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :page_comment_types
  resources :page_comments
  resources :scotty_dog_sayings
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations

  match '/courses/current_semester' => redirect("/courses/semester/#{AcademicCalendar.current_semester()}#{Date.today.year}"), :as => :current_semester
  match '/courses/next_semester' => redirect("/courses/semester/#{AcademicCalendar.next_semester()}#{AcademicCalendar.next_semester_year}"), :as => :next_semester
  match '/course/:course_id/grades/send_final_grade' => 'grades#send_final_grade', :as=>:send_final_grade, :via => :post
  match '/course/:course_id/grades/post_drafted_and_send' => 'grades#post_drafted_and_send', :as=>:post_drafted_and_send, :via => :post
  match '/course/:course_id/grades/save' => 'grades#save', :as=>:save, :via => :post
  match '/course/:course_id/grades/export' => 'grades#export', :as=>:export, :via => :post
  match '/course/:course_id/grades/import' => 'grades#import', :as=>:import, :via => :post

  resources :courses do
    resources :assignments
    resources :grades
  end

  match '/course/:course_id/assignments/reposition' => 'assignments#show', :as=>:assignments_show, :via => :get
  match '/course/:course_id/assignments/reposition' => 'assignments#reposition', :as=>:assignments_reposition, :via => :post

  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
        get :changed
      end
      member {post :revert}
    end
  end

  resources :page_attachments

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
      get :tool_support
    end
    resources :presentations, :only => [:new, :edit, :create, :update]
  end


  match 'courses/semester/:semester' => 'courses#index_for_semester', :as => "semester_courses"
  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people_autocomplete' => 'people#index_autocomplete'
  match '/people_search' => 'people#search'

  match '/people_csv' => 'people#download_csv'
  match '/people_vcf' => 'people#download_vcf'

  match '/people/class_profile' => 'people#class_profile'
  match '/people/ajax_check_if_email_exists' => 'people#ajax_check_if_email_exists'
  match '/people/ajax_check_if_webiso_account_exists' => 'people#ajax_check_if_webiso_account_exists'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses_verbose' => 'people#my_courses_verbose', :as => :my_courses
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  match '/people/:id/upload_photo' => 'people#upload_photo', :as => :people_photo_upload, :via => :put
  resources :people
  resources :users, :controller => 'people'
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams



  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new', :via => :get
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv_old' => 'teams#export_to_csv'
  match 'courses/:course_id/export_to_csv' => 'courses#export_to_csv'
  match 'courses/:course_id/team_formation_tool' => 'courses#team_formation_tool', :as => :team_formation_tool
  match 'courses/:course_id/student_grades' => 'grades#student_deliverables_and_grades_for_course', :as => :course_student_grades
  match 'courses/:course_id/deliverables' => 'deliverables#grading_queue_for_course', :as => :course_deliverables
  match 'courses/:course_id/get_deliverables' => 'deliverables#get_deliverables', :as => :get_deliverables
  match 'courses/:course_id/filter_deliverables' => 'deliverables#filter_deliverables', :as => :filter_deliverables
  match 'courses/:course_id/update_feedback' => 'deliverables#update_feedback', :as => :update_feedback
  match 'courses/:course_id/presentations' => 'presentations#index_for_course', :as => :course_presentations



  #match 'courses/:course_id/presentations/update' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/edit' => 'presentations#edit', :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#new', :as => :new_course_presentation

  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'

  match 'static/:action' => 'static#:action'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root

end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  layout 'cmu_sv'

  before_filter :authenticate_user!

  # GET /task_types
  # GET /task_types.xml
  def index
#    @task_types = TaskType.locate_appropriate_by_user_type
    @task_types = locate_appropriate_by_user_type
    ##
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @task_types }
    end
  end

  # GET /task_types/1
  # GET /task_types/1.xml
  def show
    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @task_type }
    end
  end

  # GET /task_types/new
  # GET /task_types/new.xml
  def new
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
      redirect_to(task_types_url) and return
    end

    @task_type = TaskType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @task_type }
    end
  end

  # GET /task_types/1/edit
  def edit
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
      redirect_to(task_type_url) and return
    end

    @task_type = TaskType.find(params[:id])
  end

  # POST /task_types
  # POST /task_types.xml
  def create
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
      redirect_to(task_types_url) and return
    end

    @task_type = TaskType.new(params[:task_type])

    respond_to do |format|
      if @task_type.save
        flash[:notice] = 'TaskType was successfully created.'
        format.html { redirect_to(@task_type) }
        format.xml { render :xml => @task_type, :status => :created, :location => @task_type }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @task_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /task_types/1
  # PUT /task_types/1.xml
  def update
    if !(current_user.is_admin? || current_user.is_staff?)
      flash[:error] = "You don't have permission to do this action."
      redirect_to(task_type_url) and return
    end

    @task_type = TaskType.find(params[:id])

    respond_to do |format|
      if @task_type.update_attributes(params[:task_type])
        flash[:notice] = 'TaskType was successfully updated.'
        format.html { redirect_to(@task_type) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @task_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.xml
  def destroy
    if !current_user.is_admin?
      flash[:error] = 'You don' 't have permission to do this action.'
      redirect_to(task_types_url) and return
    end

    @task_type = TaskType.find(params[:id])
    @task_type.destroy

    respond_to do |format|
      format.html { redirect_to(task_types_url) }
      format.xml { head :ok }
    end
  end

  private
  def locate_appropriate_by_user_type
    if current_user.is_student? && current_user.is_staff?
      task_types = TaskType.all
    end
    if current_user.is_student? && !current_user.is_staff?
      task_types = TaskType.where(:is_student => true).all
    end
    if !current_user.is_student? && current_user.is_staff?
      task_types = TaskType.where(:is_staff => true).all
    end
    if !current_user.is_student? && !current_user.is_staff?
      task_types = TaskType.all
    end
    return task_types
  end
end

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= form_for(@task_type) do |f| %>
    <% if @task_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task type from being saved:</h2>

          <ul>
            <% @task_type.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description, :size => "80x10" %>
    </p>
    <p>
      <%= f.label :is_staff %><br/>
      <%= f.check_box :is_staff %>
    </p>
    <p>
      <%= f.label :is_student %><br/>
      <%= f.check_box :is_student %>
    </p>
    <p>
      <%= f.submit "Update" %>
    </p>
<% end %>

<p><%= link_to 'Show', @task_type %> |
  <%= link_to 'Back', task_types_path %></p>

app/views/task_types/index.html.erb
<h1>Listing Task Types</h1>

<table class="cmu_table">
  <tr>
    <th width="150">Name</th>
    <th>Description</th>
    <!--
    <th>Is staff</th>
    <th>Is student</th>
    -->
  </tr>

  <% for task_type in @task_types %>
      <tr class="<%= cycle('cmu_table_odd', 'cmu_table_even') %>">
        <td><%= h task_type.name %></td>
        <td><%= h task_type.description %></td>
        <!--
    <td><%= h "x" if task_type.is_staff %></td>
    <td><%= h "x" if task_type.is_student %></td>
-->
        <% if current_user.is_admin? %>
            <td><%= link_to 'Show', task_type %></td>
            <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
            <td><%= link_to 'Destroy', task_type, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>

<% if current_user.is_admin? %> <p><%= link_to 'New task_type', new_task_type_path %></p>
<% end %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= form_for(@task_type) do |f| %>
    <% if @task_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task type from being saved:</h2>

          <ul>
            <% @task_type.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description, :size => "80x10" %>
    </p>
    <p>
      <%= f.label :is_staff %><br/>
      <%= f.check_box :is_staff %>
    </p>
    <p>
      <%= f.label :is_student %><br/>
      <%= f.check_box :is_student %>
    </p>
    <p>
      <%= f.submit "Create" %>
    </p>
<% end %>

<p><%= link_to 'Back', task_types_path %></p>

app/views/task_types/show.html.erb
<p>
  <b>Name:</b>
  <%= h @task_type.name %>
</p>

<p>
  <b>Description:</b>
  <%= h @task_type.description %>
</p>

<p>
  <b>Is staff:</b>
  <%= h @task_type.is_staff %>
</p>

<p>
  <b>Is student:</b>
  <%= h @task_type.is_student %>
</p>


<p><%= link_to 'Edit', edit_task_type_path(@task_type) %> |
  <%= link_to 'Back', task_types_path %></p>