config/routes.rb
CMUEducation::Application.routes.draw do


  #temporary for Mel
  match 'courses/:course_id/team_deliverables' => 'deliverables#team_index_for_course', :as => :individual_deliverables
  match 'courses/:course_id/individual_deliverables' => 'deliverables#individual_index_for_course', :as => :team_deliverables

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  constraints(:host => /rails.sv.cmu.edu/) do
    match "/(*path)" => redirect {|params, req| "http://whiteboard.sv.cmu.edu/#{params[:path]}"}
  end

  resources :search, :only => [:index]
  #get    "/deliverables/get_assignments_for_student(.:format)" =>  "deliverables#get_assignments_for_student"

  resources :password_resets

  match '/deliverables/get_assignments_for_student(.:format)'=> 'deliverables#get_assignments_for_student' ,:as=> :get_assignments_for_student
  resources :deliverables

  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/people/:id/my_presentations' => 'presentations#my_presentations', :as => :my_presentations

  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/presentations/:id/show_feedback' => 'presentations#show_feedback', :as => :show_feedback_for_presentation, :via => :get
  match '/presentations/:id/edit_feedback' => 'presentations#update_feedback', :via => :put
  match '/presentations/:id/edit_feedback' => 'presentations#edit_feedback', :as => :edit_feedback_for_presentation, :via => :get
  match '/presentations/:id/feedback' => 'presentations#create_feedback', :via => :post
  match '/presentations/:id/feedback' => 'presentations#new_feedback', :as => :new_presentation_feedback, :via => :get
  match '/presentations/today' => 'presentations#today', :as => :today_presentations
  resources :presentations, :only => [:index]

  match '/jobs/assignments' => 'jobs#assignments', :as => :job_assignments
  resources :jobs

  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :page_comment_types
  resources :page_comments
  resources :scotty_dog_sayings
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations

  match '/courses/current_semester' => redirect("/courses/semester/#{AcademicCalendar.current_semester()}#{Date.today.year}"), :as => :current_semester
  match '/courses/next_semester' => redirect("/courses/semester/#{AcademicCalendar.next_semester()}#{AcademicCalendar.next_semester_year}"), :as => :next_semester
  match '/course/:course_id/grades/send_final_grade' => 'grades#send_final_grade', :as=>:send_final_grade, :via => :post
  match '/course/:course_id/grades/post_drafted_and_send' => 'grades#post_drafted_and_send', :as=>:post_drafted_and_send, :via => :post
  match '/course/:course_id/grades/save' => 'grades#save', :as=>:save, :via => :post
  match '/course/:course_id/grades/export' => 'grades#export', :as=>:export, :via => :post
  match '/course/:course_id/grades/import' => 'grades#import', :as=>:import, :via => :post

  resources :courses do
    resources :assignments
    resources :grades
  end

  match '/course/:course_id/assignments/reposition' => 'assignments#show', :as=>:assignments_show, :via => :get
  match '/course/:course_id/assignments/reposition' => 'assignments#reposition', :as=>:assignments_reposition, :via => :post

  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
        get :changed
      end
      member {post :revert}
    end
  end

  resources :page_attachments

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
      get :tool_support
    end
    resources :presentations, :only => [:new, :edit, :create, :update]
  end


  match 'courses/semester/:semester' => 'courses#index_for_semester', :as => "semester_courses"
  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people_autocomplete' => 'people#index_autocomplete'
  match '/people_search' => 'people#search'

  match '/people_csv' => 'people#download_csv'
  match '/people_vcf' => 'people#download_vcf'

  match '/people/class_profile' => 'people#class_profile'
  match '/people/ajax_check_if_email_exists' => 'people#ajax_check_if_email_exists'
  match '/people/ajax_check_if_webiso_account_exists' => 'people#ajax_check_if_webiso_account_exists'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses_verbose' => 'people#my_courses_verbose', :as => :my_courses
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  match '/people/:id/upload_photo' => 'people#upload_photo', :as => :people_photo_upload, :via => :put
  resources :people
  resources :users, :controller => 'people'
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams



  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new', :via => :get
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv_old' => 'teams#export_to_csv'
  match 'courses/:course_id/export_to_csv' => 'courses#export_to_csv'
  match 'courses/:course_id/team_formation_tool' => 'courses#team_formation_tool', :as => :team_formation_tool
  match 'courses/:course_id/student_grades' => 'grades#student_deliverables_and_grades_for_course', :as => :course_student_grades
  match 'courses/:course_id/deliverables' => 'deliverables#grading_queue_for_course', :as => :course_deliverables
  match 'courses/:course_id/get_deliverables' => 'deliverables#get_deliverables', :as => :get_deliverables
  match 'courses/:course_id/filter_deliverables' => 'deliverables#filter_deliverables', :as => :filter_deliverables
  match 'courses/:course_id/update_feedback' => 'deliverables#update_feedback', :as => :update_feedback
  match 'courses/:course_id/presentations' => 'presentations#index_for_course', :as => :course_presentations



  #match 'courses/:course_id/presentations/update' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/edit' => 'presentations#edit', :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#new', :as => :new_course_presentation

  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'

  match 'static/:action' => 'static#:action'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'cmu_sv'

  def index
    @rss_feeds = RssFeed.all

    if (current_person.nil?)
      @registered_for_these_courses_during_current_semester = []
      @teaching_these_courses_during_current_semester = []
    else
      @registered_for_these_courses_during_current_semester = current_person.registered_for_these_courses_during_current_semester
      @teaching_these_courses_during_current_semester = current_person.teaching_these_courses_during_current_semester
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @courses }
    end
  end

  def new_features
  end

  def configuration

  end

end

app/views/welcome/configuration.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title></title>
</head>
<body>


<div>Google Username: <%= GOOGLE_USERNAME %></div>
<div>Google Domain: <%= GOOGLE_DOMAIN %></div>
<br/>

<div>TWiki Username: <%= TWIKI_USERNAME %></div>
<div>TWiki Url: <%= TWIKI_URL %></div>
<br/>


<h2>Http Headers</h2>
<table border="1">
<% for header in request.env.select {|k,v| k.match("^HTTP.*")} %>
  <tr>
    <td><%=header[0].split('_',2)[1]%></td><td><%=header[1]%></td>
  </tr>
<% end %>
</table>


<table border="1">
<% for header in request.env %>
  <tr>
    <td><%=header[0].split('_',2)[1]%></td><td><%=header[1]%></td>
  </tr>
<% end %>
</table>




</body>
</html>

app/views/welcome/index.html.erb
<% content_for :title, 'Whiteboard LMS for CMU-SV' %>

<%# render :partial=>'rss_feeds/index', :locals => {:rss_feeds => @rss_feeds} %>

<h1>Whiteboard.sv.cmu.edu</h1>

<form action="<%= search_index_path %>" id="searchform" method="get" role="search">
  <div>
    <label for="s" class="screen-reader-text">Search for:</label>
    <input type="text" id="query" name="query" value="">
    <input type="submit" value="Search" id="searchsubmit">
    (Note: searches through curriculum pages)
  </div>
</form>

<% if current_user %>
    <table class="layout_table">
      <tr>
        <td>
          <%= render :partial => "/courses/my_courses" %>
        </td>
        <td>
          <h1>Pages</h1>
          <%= link_to "Orientation", "/pages/orientation" %>
        </td>
      </tr>
    </table>
<% end %>


<% if current_user && (current_user.is_staff || current_user.is_admin) %>
    <h2>Faculty views</h2>
    <p><a href="/teams">All teams</a></p>
    <h2>Admin notes</h2>
    <p>The current semester is <%= current_semester() %>. The current time is <%= l Time.now, :format => :chatty %> </p>
<% end %>

<h2>New features</h2>
<p><%= link_to "New Features", new_features_path %></p>
<p><%= link_to "Google Mailing Lists", mailing_lists_path %></p>

<% if current_user && current_user.is_admin %>
    <h2>Admin only</h2>
    <p><%= link_to "Config", config_path %></p>
<% end %>

app/views/welcome/new_features.erb
<% content_for :title, 'New Features' %>

<p>6/13/2013</p> - <b>Upload and select photo</b> - Users can now upload their own photo, and select which photo they want to be seen in the system

<p>6/06/2013</p> - <b>Revert page</b> - Thanks to Norman Xin for adding page revert

<p>5/31/2013</p> - <b>Reorder assignments</b> - Thanks to team bug (Edward Akoto, Shama Hoque, Lydian Lee, Clyde Li)

<p>3/7/2013</p> - <b>Multiple editors warning</b> - Now, thanks to Team Number Crunchers, mulitple editors working on the same
page is prevented until a certain period of inactivity passes

<p>2/28/2013</p> - <b>Suggest new page</b> -- thanks to team Number Crunchers (Minh Pham, Jason Leng, Mike Vrooman,
Brian Bailey) and team Procrastination (Morgan Brown, Gio Perez, Victor Marmol, Sion Chaudhuri) for the code
that suggests a new page when the user tries to access one that doesn't exist.

<p>2/28/2013</p> - <b>Autosave Peer Evaluation</b> -- thanks to team Number Crunchers (Minh Pham, Jason Leng, Mike Vrooman,
Brian Bailey) for creating the code that does an
auto-save when the user is filling in a peer evaluation.

<p>1/1/2013 - <b>Grade Book</b> -- thanks to team Leopard (Lydian Lee, Kate Liu, Prabhjot Singh) and team 3 Amigos (Madhok Shivaratre, Owen Chu, David Liu) for implementing the gradebook functionality. </p>

<p>1/1/2013 - <b>New People Search</b>Thanks to Team Ramrod (Kaushik Gopal, Edward Akoto, Zhipeng Li, David Pfeffer) for providing a complete rewrite for the people search and user
profile pages. The new user interface is gorgeous. The pull request was extremely easy to integrate.</p>

<p>11/24/2012</p> - <b></b> -- thanks to Team Procrastinators (Morgan Brown, Gio Perez, Victor Marmol, Sion Chaudhuri) for adding in unescaped fields for HTML output in lib/HUB_class_roster_handler.rb's roster_change_message.
</p>


<p>11/22/2012 - <b>Edit Presentation Feedback</b> -- thanks to Team Bean Counters (Craig Hokanson, Tim Zaitsev, James Ricks). Now you can
  edit presentation feedback you just saved.</p>

<p>5/1/2012 - <b>HUB integration</b> -- thanks to Isak Sky and some love from Todd, we are able to take HUB course
  registration and </p>

<p>3/15/2012 - <b>Bug fixes</b> -- thanks to team Dante's Peak for fixing some of the Academic Calendar issues and team
  Unstoppable for fixing twiki css and potential person issues. </p>

<p>1/24/2012 - <b>Page attachments</b> -- thanks to Isak Sky and team Gandalf IRL for allowing us to attach files to the
  curriculum pages. </p>

<p>12/1/2011 - <b>Better print pages</b> -- thanks to Mag Lev for fixing the print page and print teams bugs</p>

<p>11/29/2011 - <b>Faster Tests</b> -- thanks to Unstoppable for speeding up slow tests </p>

<p>11/10/2011 - <b>New Tests</b> -- thanks for Airport 77, Gandalf IRL, Mavericks for providing excellent model and
  controller tests</p>

<p>5/11/2011 - <b>Deliverables</b> - Thanks to Team Super 8 for Deliverable Submission feature. We can now move off of
  tigris.org MFSE (Story 1 Fall 2010). </p>

<p>4/19/2011 - <b>Upload Profile Photo</b> - Thanks to Team Veracity for allowing users to change their photo </p>

<p>4/15/2011 - <b>Team Formation Helper</b> - Thanks to Team Super8 for creating a helper that allows faculty to see who
  has been on which team in the past and exporting it out to csv. This is MFSE - Story 6 Fall 2010.</p>

<p>4/15/2011 - <b>Edit Profile</b> - Thanks to Team Super8 for polishing up the Edit Profile code from the MFSE (Story
  11 Fall 2010).</p>

<p>4/1/2011 - <b>Sponsored Project Research</b> - Chris Jensen and Todd Sedano added code to make Hector's life a bit
  easier.</p>

<p>10/15/2010 - <b>CMS</b> prototype of curriculum website is now ready</p>

<p>9/30/2010 - <b>Papers</b> prototype of papers is now ready.</p>

<p>7/1/2010 - <b>New production environment</b> -- our move to Heroku happened around here</p>

<p>5/15/2010 - <b>Auto create google and twiki accounts</b> When a new user is created, the system can create a
  correspoinding sv.cmu.edu email account and twiki account.</p>

<p>4/30/2010 - Thanks to Suresh Rajasekaran for writing code to see if a user is logging effort against the wrong
  courses.</p>

<p>4/1/2010 - <b>Team Email Lists</b> - are now created automatically - Thanks to Team Deming for providing this code in
  MfSE.</p>
<p>3/18/2010 - <b>Mailing Lists</b> - We can now see what <%= link_to "Google Mailing Lists", mailing_lists_path %>
  exist and who is on each one</p>

<p>3/14/2010 - Effort Logs can be created on Monday of the following week - Thanks to Team Crosby for providing this
  code in Mfse.
  Special thanks for providing all the test cases to verify that the code works properly.</p>

<p>3/2/2010 - <b>My Teams (faculty view)</b> - Thanks to Team Juran for providing this code in MfSE.
  Faculty can now easily see which teams they are teaching</p>

<p>2/23/2010 - <b>My Teams</b> - Thanks to Team Juran for providing this code in MfSE.
  Students can now easily see which teams they are on</p>

<p>2/5/2010 - <b>Peer Evalution tool integrated!</b>- Russel Reed wrote the initial version of the Peer
  Evaluation tool which allows faculty members to record student learning objectives.
  Student teams can do a 360 peer evaluation. Faculty can quickly see who hasn't
  done the evaluation. The tool also generates a draft report for each student.
  This entire process used to be very tedious for the faculty since we had to both
  setup Survey Monkey and manually generate the student reports.
</p>


<p>
  12/31/2009 - Added in Team Deming code from MfSE for sorting courses. Special
  thanks to Evgueni Ratchev, Harish Suvarna, Gayatri Picha, Greg Hilton, and
  Andrew Retelle for making this possible.
</p>

<p>
  12/16/2009 - <b>RSS Integration</b> - Any news articles published on http://sv.cmu.edu
  are linked from the rails app's home page.
</p>

<p>
  11/30/2009 - Integrated twiki user page into rails database. Started the process
  of moving user data from TWiki to rails database
</p>

<p>10/26/2009 - Photo Book created</p>

<p>10/22/2009 - List all email addresses for a course (for Ron)</p>

<p>10/19/2009 - configured apache and mongrel to allow the browser to cache static
  content (ie images, javascript, css)</p>

<p>10/16/2009 - This project is now under continuous integration on a build machine!</p>

<p>10/7/2009 - Effort Logs - Faculty now get weekly reminders to check effort logs
  for their courses.</p>

<p>9/4/2009 - User Data - this project now has all the data fields found in the
  twiki application.</p>

<p>6/26/2009 - <b>Curriculum Website Comments</b> - Implemented feature suggested by
  Mania Orand.</p>

<p>5/22/2009 - <b>Scotty Dog</b> is born and sends his first email.</p>

<p>3/25/2009 - Tablesorter introducted for people data and course data.</p>

<p>2/3/2009 - Effort Log for faculty. Now faculty can dog food!</p>

<p>1/16/2009 - <b>Suggestion Box</b> for new features and bug fixes</p>

<p>9/30/2008 - <b>Effort Reports</b></p>

<p>8/14/2008 - Andrew Id integration. </p>

<p>7/22/2008 - <b>Effort Log for students.</b></p>

<p>7/1/2008 - project started</p>