config/routes.rb
CMUEducation::Application.routes.draw do


  #temporary for Mel
  match 'courses/:course_id/team_deliverables' => 'deliverables#team_index_for_course', :as => :individual_deliverables
  match 'courses/:course_id/individual_deliverables' => 'deliverables#individual_index_for_course', :as => :team_deliverables

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  constraints(:host => /rails.sv.cmu.edu/) do
    match "/(*path)" => redirect {|params, req| "http://whiteboard.sv.cmu.edu/#{params[:path]}"}
  end

  resources :search, :only => [:index]
  #get    "/deliverables/get_assignments_for_student(.:format)" =>  "deliverables#get_assignments_for_student"

  resources :password_resets

  match '/deliverables/get_assignments_for_student(.:format)'=> 'deliverables#get_assignments_for_student' ,:as=> :get_assignments_for_student
  resources :deliverables

  match '/people/:id/my_deliverables' => 'deliverables#my_deliverables', :as => :my_deliverables
  match '/people/:id/my_presentations' => 'presentations#my_presentations', :as => :my_presentations

  match '/deliverables/:id/feedback' => 'deliverables#edit_feedback', :as => :deliverable_feedback
  match '/presentations/:id/show_feedback' => 'presentations#show_feedback', :as => :show_feedback_for_presentation, :via => :get
  match '/presentations/:id/edit_feedback' => 'presentations#update_feedback', :via => :put
  match '/presentations/:id/edit_feedback' => 'presentations#edit_feedback', :as => :edit_feedback_for_presentation, :via => :get
  match '/presentations/:id/feedback' => 'presentations#create_feedback', :via => :post
  match '/presentations/:id/feedback' => 'presentations#new_feedback', :as => :new_presentation_feedback, :via => :get
  match '/presentations/today' => 'presentations#today', :as => :today_presentations
  resources :presentations, :only => [:index]

  match '/jobs/assignments' => 'jobs#assignments', :as => :job_assignments
  resources :jobs

  match '/sponsored_projects/:id/archive' => 'sponsored_projects#archive', :as => :archive_sponsored_project
  match '/sponsored_project_sponsors/:id/archive' => 'sponsored_project_sponsors#archive', :as => :archive_sponsored_project_sponsor
  match '/sponsored_project_allocations/:id/archive' => 'sponsored_project_allocations#archive', :as => :archive_sponsored_project_allocation
  resources :sponsored_projects
  resources :sponsored_project_sponsors
  resources :sponsored_project_allocations
  resources :sponsored_project_efforts
  match 'delayed_system_jobs/' => 'delayed_system_jobs#index'
  resources :delayed_system_jobs
  resources :rss_feeds
  resources :page_comment_types
  resources :page_comments
  resources :scotty_dog_sayings
  resources :task_types
  match '/effort_logs/update_task_type_select' => 'effort_logs#update_task_type_select', :as => :update_task_type_select
  match '/effort_logs/effort_for_unregistered_courses' => 'effort_logs#effort_for_unregistered_courses'
  resources :effort_logs
  resources :effort_log_line_items
  resources :effort_log_line_items
  resources :course_numbers
  resources :course_configurations

  match '/courses/current_semester' => redirect("/courses/semester/#{AcademicCalendar.current_semester()}#{Date.today.year}"), :as => :current_semester
  match '/courses/next_semester' => redirect("/courses/semester/#{AcademicCalendar.next_semester()}#{AcademicCalendar.next_semester_year}"), :as => :next_semester
  match '/course/:course_id/grades/send_final_grade' => 'grades#send_final_grade', :as=>:send_final_grade, :via => :post
  match '/course/:course_id/grades/post_drafted_and_send' => 'grades#post_drafted_and_send', :as=>:post_drafted_and_send, :via => :post
  match '/course/:course_id/grades/save' => 'grades#save', :as=>:save, :via => :post
  match '/course/:course_id/grades/export' => 'grades#export', :as=>:export, :via => :post
  match '/course/:course_id/grades/import' => 'grades#import', :as=>:import, :via => :post

  resources :courses do
    resources :assignments
    resources :grades
  end

  match '/course/:course_id/assignments/reposition' => 'assignments#show', :as=>:assignments_show, :via => :get
  match '/course/:course_id/assignments/reposition' => 'assignments#reposition', :as=>:assignments_reposition, :via => :post

  constraints({:id => /.*/}) do
    resources :mailing_lists
    resources :pages do
      collection do
        post :reposition
        get :changed
      end
      member {post :revert}
    end
  end

  resources :page_attachments

  resources :course_navigations
  resources :courses do
    resources :teams do
    end
    member do
      get :configure
      get :tool_support
    end
    resources :presentations, :only => [:new, :edit, :create, :update]
  end


  match 'courses/semester/:semester' => 'courses#index_for_semester', :as => "semester_courses"
  match '/courses/:course_id/peer_evaluations' => 'peer_evaluation#index_for_course', :via => :get, :as => "peer_evaluations"
  match '/courses/:course_id/teams/:id/peer_evaluation' => 'teams#peer_evaluation', :via => :get, :as => "peer_evaluation"
  match '/courses/:course_id/teams/:id/peer_evaluation_update' => 'teams#peer_evaluation_update', :via => :post, :as => "peer_evaluation_update"
  match 'peer_evaluation/edit_setup/:id' => 'peer_evaluation#edit_setup', :as => :setup_peer_evaluation
  match 'peer_evaluation/edit_evaluation/:id' => 'peer_evaluation#edit_evaluation', :as => :edit_peer_evaluation
  match 'peer_evaluation/edit_report/:id' => 'peer_evaluation#edit_report', :as => :report_peer_evaluation

  match '/effort_reports/campus_week' => 'effort_reports#campus_week'
  match '/effort_reports/campus_semester' => 'effort_reports#campus_semester'
  match '/effort_reports/course/:course_id' => 'effort_reports#course'
  resources :effort_reports
  match '/people_autocomplete' => 'people#index_autocomplete'
  match '/people_search' => 'people#search'

  match '/people_csv' => 'people#download_csv'
  match '/people_vcf' => 'people#download_vcf'

  match '/people/class_profile' => 'people#class_profile'
  match '/people/ajax_check_if_email_exists' => 'people#ajax_check_if_email_exists'
  match '/people/ajax_check_if_webiso_account_exists' => 'people#ajax_check_if_webiso_account_exists'
  match '/people/advanced' => 'people#advanced' #Just in case anyone bookmarked this url
  match '/people/photo_book' => 'people#photo_book'
  match '/people/:id/my_courses_verbose' => 'people#my_courses_verbose', :as => :my_courses
  match '/people/:id/my_courses' => 'people#my_courses', :as => :my_courses
  match '/people/:id/my_teams' => 'people#my_teams', :as => :my_teams
  match '/people/:id/upload_photo' => 'people#upload_photo', :as => :people_photo_upload, :via => :put
  resources :people
  resources :users, :controller => 'people'
  resources :suggestions
  match '/teams' => 'teams#index_all', :as => :teams



  #resources :users
  #resource :user_session

  #match '/login_google' => 'user_sessions#login_google', :as => :login_google
  #match '/logout' => "user_sessions#destroy", :as => :logout


  match '/load_chart' => 'effort_reports#load_chart', :as => :load_chart
  match 'people/twiki/:twiki_name' => 'people#show_by_twiki'
  match 'twiki/teams' => 'teams#twiki_index'
  match 'twiki/teams/new' => 'teams#twiki_new', :via => :get
  match 'courses/:course_id/teams_photos' => 'teams#index_photos'
  match 'courses/:course_id/past_teams_list' => 'teams#past_teams_list', :as => :past_teams_list
  match 'courses/:course_id/export_to_csv_old' => 'teams#export_to_csv'
  match 'courses/:course_id/export_to_csv' => 'courses#export_to_csv'
  match 'courses/:course_id/team_formation_tool' => 'courses#team_formation_tool', :as => :team_formation_tool
  match 'courses/:course_id/student_grades' => 'grades#student_deliverables_and_grades_for_course', :as => :course_student_grades
  match 'courses/:course_id/deliverables' => 'deliverables#grading_queue_for_course', :as => :course_deliverables
  match 'courses/:course_id/get_deliverables' => 'deliverables#get_deliverables', :as => :get_deliverables
  match 'courses/:course_id/filter_deliverables' => 'deliverables#filter_deliverables', :as => :filter_deliverables
  match 'courses/:course_id/update_feedback' => 'deliverables#update_feedback', :as => :update_feedback
  match 'courses/:course_id/presentations' => 'presentations#index_for_course', :as => :course_presentations



  #match 'courses/:course_id/presentations/update' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/edit' => 'presentations#edit', :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#create',:via => :post, :as => :new_course_presentation
  #match 'courses/:course_id/presentations/new' => 'presentations#new', :as => :new_course_presentation

  match 'effort_reports/:id/week/:week' => 'effort_reports#show_week'
  match '/:controller(/:action(/:id))'

  match 'static/:action' => 'static#:action'
  match '/new_features' => 'welcome#new_features', :as => :new_features
  match '/config' => 'welcome#configuration', :as => :config
  match '/' => 'welcome#index', :as => :root

end

app/models/sponsored_project_effort.rb
class SponsoredProjectEffort < ActiveRecord::Base
  belongs_to :sponsored_project_allocation
  validates_presence_of :sponsored_project_allocation_id
  validates_inclusion_of :confirmed, :in => [true, false]
  validates_numericality_of :year, :month, :current_allocation, :greater_than_or_equal_to => 0
  validates_numericality_of :actual_allocation, :greater_than_or_equal_to => 0, :allow_blank => true
  validate :unique_month_year_allocation_id?

  def unique_month_year_allocation_id?
    duplicate = SponsoredProjectEffort.find_by_month_and_year_and_sponsored_project_allocation_id(self.month, self.year, self.sponsored_project_allocation_id)
    unless duplicate.nil? || duplicate.id == self.id
      errors.add(:base, "Can't create duplicate effort for the same month, year, and allocation.")
    end
  end

  scope :for_all_users_for_a_given_month,
        lambda { |month, year| {:conditions => ["month = ? and year = ?", month, year]} }

  scope :month_under_inspection_for_a_given_user,
        lambda { |user_id| {:include => :sponsored_project_allocation,
                            :conditions => ["month = ? and year = ? and sponsored_project_allocations.user_id = ?", 1.month.ago.month, 1.month.ago.year, user_id]} }


  def self.new_from_sponsored_project_allocation(allocation)

    SponsoredProjectEffort.create(:month => 1.month.ago.month, :year => 1.month.ago.year,
                                  :sponsored_project_allocation_id => allocation.id,
                                  :current_allocation => allocation.current_allocation,
                                  :actual_allocation => allocation.current_allocation,
                                  :confirmed => false)
  end

  def self.emails_business_manager(an_effort_id)
    effort = SponsoredProjectEffort.find(an_effort_id)
    SponsoredProjectEffortMailer.deliver_changed_allocation_email_to_business_manager(effort.sponsored_project_allocation.user,
                                                                                      effort.month, effort.year)
  end

end

app/controllers/sponsored_project_efforts_controller.rb
class SponsoredProjectEffortsController < ApplicationController

  before_filter :authenticate_user!

  layout "cmu_sv"

  def index
    authorize! :read, SponsoredProjectEffort
    @month = params[:date][:month].to_i unless params[:date].nil?
    @month = @month ||= 1.month.ago.month
    @year = params[:year] ||= 1.month.ago.year
    @efforts = SponsoredProjectEffort.for_all_users_for_a_given_month(@month, @year)
  end

  def show
    redirect_to(edit_sponsored_project_effort_path)
  end

  def edit
    if authorized_or_redirect
      setup_edit
    end
  end

  def update
    if authorized_or_redirect
      effort_id_values = params[:effort_id_values]

      @failed = false
      @changed_allocation = false
      effort_id_values.each do |key, value|
        effort = SponsoredProjectEffort.find(key)
        #      @changed_allocation = true if effort.actual_allocation != value
        effort.actual_allocation = value
        @changed_allocation = true if effort.actual_allocation_changed?
        effort.confirmed = true
        unless effort.save
          @failed = true
        end
      end
      if @changed_allocation
        SponsoredProjectEffort.emails_business_manager(effort_id_values.keys[0])
      end

      if @failed
        flash.now[:error] = 'Your allocations did not save.'
      else
        flash.now[:notice] = 'Your allocations are confirmed.'
      end

      setup_edit
      render 'edit'
    end
  end

  private
  #Todo: refactor this method to use CanCan
  def authorized_or_redirect
    @user = User.find_by_twiki_name(params[:id])
    if (@user.nil?)
      flash[:error] = t(:no_person)
      redirect_to(root_path)
      return false
    end

    unless @user.id == current_user.id || can?(:update, SponsoredProjectEffort)
      flash[:error] = t(:no_permission)
      redirect_to(root_path)
      return false
    end
    return true
  end

  def setup_edit
    @efforts = SponsoredProjectEffort.month_under_inspection_for_a_given_user(@user.id)
    @month = !@efforts.empty? ? @efforts[0].month : 1.month.ago.month
    @year = !@efforts.empty? ? @efforts[0].year : 1.month.ago.year
  end

end

app/views/sponsored_project_efforts/_form.html.erb
<%= form_tag sponsored_project_effort_path, :method => :put do %>


    <table id="effort_table" class="tablesorter" cellpadding="3">
      <thead>
      <tr>
        <th>Sponsor</th>
        <th>Project</th>
        <th>Planned Allocation</th>
        <th>Actual Allocation</th>
      </tr>
      </thead>
      <tbody>

      For the month of <%= monthname(@month) %>, our records show that your effort was distributed as follows:

      <% @efforts.each do |effort| %>
          <tr>
            <td><%= effort.sponsored_project_allocation.sponsored_project.sponsor.name %></td>
            <td><%= effort.sponsored_project_allocation.sponsored_project.name %></td>
            <td><%= effort.current_allocation %> </td>
            <td><%= text_field_tag "effort_id_values[#{effort.id}]", effort.actual_allocation, :size => 2 %> %</td>
          </tr>
      <% end %>


      </tbody>
    </table>

    Is this distribution a correct approximation of your effort?
    <br/>
    <br/>
    <%= submit_tag "I confirm this to be accurate" %>
    <br/>
    <br/>
<% end %>

app/views/sponsored_project_efforts/edit.html.erb
<h1><%= monthname(@month) %> <%= @year %></h1>

<%= render :partial => "form", :locals => {:button_name => "Update"} %>

<% if current_user.permission_level_of(:admin) %>
    <%= link_to 'Back', sponsored_project_efforts_path %>
<% end %>
<br/>
<br/>

app/views/sponsored_project_efforts/index.html.erb
<% content_for :tablesorter do %>

    <%= javascript_include_tag 'jquery_tablesorter_min.js' %>
    <%= javascript_include_tag 'jquery_quicksearch.js' %>

    <script type="text/javascript">
        $(document).ready(function () {
            var $search = $("#filterBoxOne");
            if ($search.prop("disabled") == true) {
                $search.val('');
                $search.removeAttr("disabled");
                $search.focus();
            }
            $("#effort_table").tablesorter({
                headers:{6:{sorter:false}  },
                sortList:[
                  [0, 0],
                  [1, 0]
                ]
            });
            $search.quicksearch('#effort_table tbody tr');
            //hovering over a line selects it
            $("tr").hover(function () {
                $(this).addClass("hover");
            },function () {
                $(this).removeClass("hover");
            });
        });
    </script>
<% end %>



<h1>Efforts for <%= monthname(@month) %> <%= @year %></h1>
<%= form_tag(sponsored_project_efforts_path, :method => "get") do %>
    <%= select_month @month %>
    <%= text_field_tag('year', @year, :size => '4', :maxlength => '4') %>
    <%= submit_tag 'Go' %>
<% end %>
<div class="right_link"><%= link_to 'Allocations', sponsored_project_allocations_url %>
  <br/>
  <%= link_to "Projects", sponsored_projects_url %></div>
<div style="float:none"><%= render :partial => "/people/tablesorter_filter_box" %></div>
<br/>
<table id="effort_table" class="tablesorter" cellpadding="3">
  <thead>
  <tr>
    <th>Person</th>
    <th>Sponsor</th>
    <th>Project</th>
    <th>Current Allocation</th>
    <th>Actual Allocation</th>
    <th>Confirmed</th>
  </tr>
  </thead>
  <tbody>
  <% @efforts.each do |effort| %>
      <tr class="tablesorter">
        <td><%= effort.sponsored_project_allocation.user.human_name %></td>
        <td><%= effort.sponsored_project_allocation.sponsored_project.sponsor.name %></td>
        <td><%= effort.sponsored_project_allocation.sponsored_project.name %></td>
        <td><%= effort.current_allocation %>
          % <%= link_to 'Edit', edit_sponsored_project_allocation_path(effort.sponsored_project_allocation) %>
        </td>
        <td><%= effort.actual_allocation %>
          % <%= link_to 'Edit', edit_sponsored_project_effort_path(effort.sponsored_project_allocation.user.twiki_name) %>
        </td>
        <td><%= effort.confirmed %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>
<br/>